version: '3.3'

services:
  database:
    build: ./postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: "todo"
      POSTGRES_PASSWORD: "todo"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
